### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by hook-s3c** [polaris64/syswall#2]
Would really appreciate some :) thanks!

**Comment by hook-s3c** [comment]
Is this correct?

lib;
```
cargo install syswall
```

cli;
```
cd cli
cargo build
cargo install --path .
```

**Comment by polaris64** [comment]
I'll get back to you properly when I'm back in my office, but just quickly the best bet currently is to clone the repo, then use cargo build/run (that's what I'm doing during development).

**Comment by hook-s3c** [comment]
I think that works fine now - thanks!

**Comment by polaris64** [comment]
Just for reference, `syswall_cli` has now been [published to crates.io](https://crates.io/crates/syswall_cli) and I have updated the README with installation instructions.
