### ISSUE TITLE
error: Found argument 'ls -l' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by hook-s3c** [polaris64/syswall#3]
```
$ syswall_cli ls -l
error: Found argument 'ls -l' which wasn't expected, or isn't valid in this context

USAGE:
    syswall_cli [FLAGS] [OPTIONS] [--] <tracee_cmd>...

For more information try --help
```

**Comment by hook-s3c** [comment]
is this a bug? I can't find this error string in the code

**Comment by polaris64** [comment]
The tracee command (e.g. `ls -l`) needs to be separated from the CLI-specific arguments by a `--`. So for example, you might use `syswall_cli -- ls -l` or `syswall_cli -v -- ls -l`. Hope that helps!

**Comment by hook-s3c** [comment]
ahhh, that wasn't very clear - thanks, works great now. Awesome work!
